// WARNING: generated by kopium - manual changes will be overwritten
// kopium version: 0.21.3

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use actix_web::HttpRequest;
use actix_web::HttpResponse;
use actix_web::Responder;
use actix_web::body::BoxBody;
use k8s_openapi::Metadata;
use k8s_openapi::NamespaceResourceScope;
use k8s_openapi::Resource;
use kube::api::ObjectMeta;
use serde_json::Value;

use crate::kube_types::{Artifact, Registry, Scanner};

use self::prelude::*;

#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct SbomReport {
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    pub kind: String,
    pub report: ImageSbomReport,
    pub metadata: ObjectMeta,
}

// https://github.com/kube-rs/kube/discussions/1762
impl Resource for SbomReport {
    const API_VERSION: &'static str = "aquasecurity.github.io/v1alpha1";
    const GROUP: &'static str = "aquasecurity.github.io";
    const VERSION: &'static str = "v1alpha1";
    const KIND: &'static str = "SbomReport";
    const URL_PATH_SEGMENT: &'static str = "sbomreports";
    type Scope = NamespaceResourceScope;
}

impl Metadata for SbomReport {
    type Ty = ObjectMeta;
    fn metadata(&self) -> &Self::Ty {
        &self.metadata
    }
    fn metadata_mut(&mut self) -> &mut Self::Ty {
        &mut self.metadata
    }
}

impl Responder for SbomReport {
    type Body = BoxBody;

    fn respond_to(self, _req: &HttpRequest) -> HttpResponse<Self::Body> {
        HttpResponse::Ok().json(self)
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ImageSbomReport {
    pub artifact: Artifact,
    pub components: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry: Option<Registry>,
    pub scanner: Scanner,
    pub summary: SbomReportSummary,
    #[serde(rename = "updateTimestamp")]
    pub update_timestamp: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct SbomReportSummary {
    #[serde(rename = "componentsCount")]
    pub components_count: i64,
    #[serde(rename = "dependenciesCount")]
    pub dependencies_count: i64,
}
