apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-operator-web-ui
  namespace: trivy-operator-web-ui
  labels:
    app: trivy-operator-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-operator-web-ui
  template:
    metadata:
      labels:
        app: trivy-operator-web-ui
    spec:
      serviceAccountName: trivy-operator-web-ui
      containers:
      - name: trivy-operator-web-ui
        image: ghcr.io/trivy-operator-web-ui/operator:1.0.0
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 3000
