operator:
  image:
    repository: "ghcr.io/trivy-operator-web-ui/operator"
    pullPolicy: IfNotPresent
  
  url: "dummy"

  username: "username"
  password: "password"

frontend:
  image:
    repository: "ghcr.io/trivy-operator-web-ui/frontend"
    pullPolicy: IfNotPresent
    tag: "0.1.2"