apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy-operator-web-ui

resources:
  - deployment.yaml
  - namespace.yaml
  - clusterrole.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
  - ingress.yaml
  - service.yaml