resources:
  requests:
    cpu: 200m
  limits:
    memory: 512Mi

targetNamespaces: "kube-system,trivy-operator-web-ui"

targetWorkloads: "pod,replicaset,replicationcontroller"

operator:
  scanJobsConcurrentLimit: 1