name: 🧪 Tests and Coverage

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/tests.yml"

env:
  KWOK_VERSION: "v0.7.0"
  RUST_VERSION: "1.93.1"
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: 🧪 Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout repository code
        uses: actions/checkout@v5

      - name: 🛠️ Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: ${{ env.RUST_VERSION }}

      - name: 📦 Rust cache 
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      - name: 🛠️ Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: 🛠️ Install llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: 🛠️ Install Kwok
        uses: kubernetes-sigs/kwok@main
        with:
          KWOK_VERSION: ${{ env.KWOK_VERSION}}
          command: kwokctl
      
      - name: 🛠️ Setup Kwok cluster
        run: |
          kwokctl create cluster --name=kwok
          kwokctl kubectl config set-context --current --namespace default
          kwokctl kubectl apply -f test_assets/crds/sbom_report.yaml
          kwokctl kubectl apply -f test_assets/crds/vulnerability_report.yaml
          kwokctl kubectl create namespace etcd
          kwokctl kubectl create namespace rabbit-one
          kwokctl kubectl create namespace rabbit-two

      - name: 🧪 Clippy
        run: |
          cargo clippy
        
      - name: 🧪 Unit Tests
        run: |
          cargo llvm-cov nextest test --no-fail-fast --lib -j1
